
-- account
CREATE TABLE IF NOT EXISTS account
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    age integer,
    background_color character varying(30) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    fcm_token character varying(255) COLLATE pg_catalog."default",
    image character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    remind_cycle integer,
    remind_noti_check boolean,
    remind_toggle boolean,
    sex character varying(10) COLLATE pg_catalog."default",
    social_type character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT account_pkey PRIMARY KEY (id),
    CONSTRAINT uk_q0uja26qgu1atulenwup9rxyr UNIQUE (email)
    );


ALTER TABLE account
    OWNER to yapp;


-- account_folder
CREATE TABLE IF NOT EXISTS account_folder
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    account_id bigint,
    folder_id bigint,
    CONSTRAINT account_folder_pkey PRIMARY KEY (id),
    CONSTRAINT fkpu24hyoea9vik0oexl3j8r2tu FOREIGN KEY (account_id)
    REFERENCES public.account (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
    CONSTRAINT fkq12fenyrw4agbqxdkoe9j9t0 FOREIGN KEY (folder_id)
    REFERENCES public.folder (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    );

ALTER TABLE account_folder
    OWNER to yapp;


-- folder
CREATE TABLE IF NOT EXISTS folder
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    bookmark_count integer NOT NULL,
    emoji character varying(255) COLLATE pg_catalog."default",
    index integer NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    parent_id bigint,
    CONSTRAINT folder_pkey PRIMARY KEY (id),
    CONSTRAINT fkn0cjh1seljcp0mc4tj1ufh99m FOREIGN KEY (parent_id)
    REFERENCES public.folder (id) MATCH SIMPLE
                         ON UPDATE NO ACTION
                         ON DELETE CASCADE
    );

ALTER TABLE folder
    OWNER to yapp;
