# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# github repository Actions 페이지에 나타낼 이름
name: Dotoriham CI/CD

# event trigger
on:
  push:
    branches:
      - main
      - develop
      - feature/#125-CICD

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    ## jdk setting
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' #https://github.com/actions/setup-java

    ## gradle caching
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    ## gradle build
    - name: Build with Gradle
      run: ./gradlew build -x test -x ktlintCheck -x ktlintTestSourceSetCheck -x ktlintMainSourceSetCheck

    ## docker push
    - name: Docker build & push
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t tests2 .
          docker tag tests2 ${{ secrets.DOCKER_REPO }}/tests2:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKER_REPO }}/tests2:${GITHUB_SHA::7}

    ## deploy-to-prod
    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      if: contains(github.ref, 'main')
      with:
          host: ec2-3-36-38-219.ap-northeast-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
              docker pull ${{ secrets.DOCKER_REPO }}/tests2:${GITHUB_SHA::7}
              docker tag ${{ secrets.DOCKER_REPO }}/tests2:${GITHUB_SHA::7} tests
              docker stop server
              docker run -d --rm --name server -p 8079:8079 -e PROFILE=prod tests

    ## deploy-to-dev
    - name: Deploy to dev
      uses: appleboy/ssh-action@master
      if: contains(github.ref, 'feature/#125-CICD')
      with:
        host: ec2-52-79-62-36.ap-northeast-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}/tests2:${GITHUB_SHA::7}
            PROFILE=dev docker-compose up -d
            docker image prune -f
