# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# github repository Actions 페이지에 나타낼 이름
name: Dotoriham CI/CD

# event trigger
on:
  push:
    branches:
      - main
      - develop
      - feature/#125-CICD

permissions:
  contents: read

jobs:
  ## jdk setting & gradle caching
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/checkout@v3
      with:
        java-version: '11'
        distribution: 'temurin' # https://github.com/actions/setup-java

    - name: Gradle Caching
      uses: actions/checkout@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
  ## gradle build
  gradle-build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Build with Gradle
      run: ./gradlew build -x test -x ktlintCheck -x ktlintTestSourceSetCheck -x ktlintMainSourceSetCheck -x ktlintKotlinScriptCheck

  ## docker build & push
  docker-build-push:
    needs: [setup, gradle-build]
    runs-on: ubuntu-latest
    steps:
    
    ## build & push to prod
    - name: Docker build & push to prod
      if: contains(github.ref, 'main')
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-prod -t juhyun419/dotoriham-prod .
          docker push ${{ secrets.DOCKER_REPO }}/dotoriham-prod

    ## build & push to dev
    - name: Docker build & push to dev
      if: contains(github.ref, 'feature/#125-CICD')
      run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-dev -t ${{ secrets.DOCKER_REPO }}/dotoriham-dev .
          docker push ${{ secrets.DOCKER_REPO }}/dotoriham-dev

  ## deploy to server
  deploy:
    needs: [setup, gradle-build, docker-build-push]
    runs-on: ubuntu-latest
    steps:
    
    ## deploy to prod
    - name: Deploy to prod
      uses: appleboy/ssh-action@master
      id: deploy-prod
      if: contains(github.ref, 'main')
      with:
          host: ec2-3-36-38-219.ap-northeast-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
              sudo docker rm -f $(docker ps -qa)
              sudo docker pull ${{ secrets.DOCKER_REPO }}/dotoriham-prod
              docker-compose up -d
              docker image prune -f

    ## deploy to dev
    - name: Deploy to dev
      uses: appleboy/ssh-action@master
      id: deploy-dev
      if: contains(github.ref, 'feature/#125-CICD')
      with:
        host: ec2-52-79-62-36.ap-northeast-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_REPO }}/dotoriham-dev
            docker-compose up -d
            docker image prune -f

  ## slack
  slack-message:
    needs: [setup, gradle-build, docker-build-push, deploy]
    runs-on: ubuntu-latest
    steps:
    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
          status: ${{ job.status }}
          author_name: GitHub-Actions CI/CD
          fields: repo,message,commit,author,ref,job,took
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.

  ## remind failure on workflow
#   fail-check:
#     needs: [setup, gradle-build, docker-build-push, deploy]
#     runs-on: ubuntu-latest
#     steps:
#     - name: Push on failure
#       uses: 8398a7/action-slack@v3
#       with:
#           status: ${{ job.status }}
# #          text: ':fail: Failed GitHub Actions'
#           author_name: GitHub-Actions CI/CD
#           fields: repo,message,commit,author,ref,job,took
#       env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
#       if: steps.deploy-prod != 'success' || steps.deploy-dev != 'success'
